---
# defaults file for PG
#------------------------------------------------------------------------------
# PostgreSQL   environment
#------------------------------------------------------------------------------
# - dbsu - #
pg_db_su: postgres
pg_db_uid: 26
pg_db_sudo: nopass
os_home: /home/postgres
pg_db_home: /home/postgres/local
pg_db_home_soft: /usr/local/soft
pg_dbsu_ssh_exchange: true                    # exchange postgresql dbsu ssh key among same cluster ?


# -dbip  #
#mange_ip: '82.157.166.95'
mange_inspection: /root/vb_auto_app/roles/pg/files/db_inspection/resluts
#mange_check: /root/vb_auto_app/roles/vb/files/db_check/resluts

# - postgresql packages - #
pg_version: 11
pg_packages:                                  # postgresql related packages. `${pg_version} will be replaced by `pg_version`
  - postgresql${pg_version}*                  # postgresql kernel packages
  - postgis31_${pg_version}*                  # postgis
  - pgbouncer patroni pg_exporter pgbadger    # 3rd utils
  - patroni patroni-consul patroni-etcd pgbouncer pgbadger pg_activity
  - python3 python3-psycopg2 python36-requests python3-etcd python3-consul
  - python36-urllib3 python36-idna python36-pyOpenSSL python36-cryptography

db_extensions:
  - pg_stat_statements


# - storage - #
pg_data: /home/postgres/data
pg_an_conf: /usr/local/db_pgsql                # postgresql ansible main and backup dir
pg_dcs_conf: /usr/local/db_pgsql_dcs 

# - connection - #
pg_listen: '0.0.0.0'                          # postgresql listen address, '0.0.0.0' (all ipv4 addr) by default
pg_port: 5432                                 # postgresql  port, 5432 by default
pg_localhost: /tmp             # localhost unix socket dir for connection

# - patroni - #
# patroni_mode, available options: default|pause|remove
#   - default: default ha mode
#   - pause:   into maintenance mode
#   - remove:  remove patroni after bootstrap
patroni_mode: default                         # pause|default|remove
vb_namespace: /postgres                            # top level key namespace in dcs
patroni_port: 8008                            # default patroni port
patroni_watchdog_mode: automatic              # watchdog mode: off|automatic|required
#vb_conf: vb.yml                             # pgsql template:  {oltp|olap|crit|tiny}.yml , use tiny for sandbox
# use oltp|olap|crit for production, or fork your own templates (in ansible templates dir)
vb_shared_libraries: 'pg_stat_statements' # extension shared libraries to be added


# - localization - #
vb_encoding: UTF8    
vb_lc_ctype: en_US.UTF8                       # database character type, en_US.UTF8 by default (for i18n full-text search)


#   log #
start_log:  /home/postgres/log.log




