#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   mian.yml
# Mtime     :   2020-05-12
# Mtime     :   2021-07-06
# Desc      :   init postgres cluster/instance
# Path      :   mian.yml
#==============================================================#

#---------------------------------------------------------------
- name:  vastbase     
  become: yes
  hosts: all
  gather_facts: no
  tags: vastbase
  roles:
    - role: vb      
