---
# tasks file for vb

#------------------------------------------------------------------------------
# prepare
#------------------------------------------------------------------------------
#- import_tasks: db_prepare.yml
  #tags: pg_prepare

#------------------------------------------------------------------------------
# install
#------------------------------------------------------------------------------
#- import_tasks: install.yml
 # tags: install


#------------------------------------------------------------------------------
# generate  report     inspection
#------------------------------------------------------------------------------
#- import_tasks: db_inspection.yml
  #tags: pg_inspection


#------------------------------------------------------------------------------
# generate  report     inspection
#------------------------------------------------------------------------------
#- import_tasks: debug_info.yml
  #tags: pg_debug_info